version: "3"

services:
  redis:
    image: redis:7.0.11
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: REDIS_PASSWORD
    volumes:
      - redis-data:/bitnami/redis/data/
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redisgraph:
    image: redislabs/redisgraph:edge
    ports:
      - "6378:6379"
    environment:
      REDIS_PASSWORD: REDIS_PASSWORD
    volumes:
      - redisgraph-data:/data

volumes:
  postgres-data:
  redis-data:
  redisgraph-data: